# Generated by Django 3.0.5 on 2022-10-08 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackpayment',
            name='user',
        ),
    ]
